version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017

    backend:
        build: .
        restart: always
        ports:
            - 80:5000
        environment: 
            DatabaseSettings__ConnectionString: "mongodb://root:example@mongo:27017"
        depends_on:
            - mongo